openapi: 3.0.0
info:
  title: Country API
  version: 1.0.0
  description: API for managing cricket countries

tags:
  - name: Country
    description: Operations related to cricket countries

paths:
  /cricket/country:
    get:
      tags:
        - Country
      summary: Get all countries
      responses:
        '200':
          description: List of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      tags:
        - Country
      summary: Create a new country
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CountryInput'
      responses:
        '201':
          description: Country created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'

  /cricket/country/{countryId}:
    get:
      tags:
        - Country
      summary: Get a country by ID
      parameters:
        - in: path
          name: countryId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Country details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '404':
          description: Country not found
    put:
      tags:
        - Country
      summary: Update a country by ID
      parameters:
        - in: path
          name: countryId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCountry'
      responses:
        '200':
          description: Country updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '404':
          description: Country not found
    delete:
      tags:
        - Country
      summary: Delete a country by ID
      parameters:
        - in: path
          name: countryId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Country deleted
        '404':
          description: Country not found

components:
  schemas:
    Country:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: India
        code:
          type: string
          example: IND
    CreateCountry:
      type: object
      required:
        - name
        - code
      properties:
        name:
          type: string
          example: India
        code:
          type: string
          example: IND