openapi: 3.0.0
info:
  title: Series API
  version: 1.0.0
  description: Series management APIs

tags:
  - name: Series
    description: Series management APIs

paths:
  /series:
    get:
      summary: Get all series
      tags:
        - Series
      responses:
        '200':
          description: List of series
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Series'
    post:
      summary: Create a new series
      tags:
        - Series
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateSeries'
      responses:
        '201':
          description: Series created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Series'

  /series/{seriesId}:
    get:
      summary: Get a series by ID
      tags:
        - Series
      parameters:
        - in: path
          name: seriesId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Series details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Series'
        '404':
          description: Series not found
    put:
      summary: Update a series by ID
      tags:
        - Series
      parameters:
        - in: path
          name: seriesId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSeries'
      responses:
        '200':
          description: Series updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Series'
        '400':
          description: Invalid series ID
        '404':
          description: Series not found
    delete:
      summary: Delete a series
      tags:
        - Series
      parameters:
        - in: path
          name: seriesId
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Series deleted

  /series/{seriesId}/hosts:
    put:
      summary: Update host countries for a series
      tags:
        - Series
      parameters:
        - in: path
          name: seriesId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSeriesHosts'
      responses:
        '200':
          description: Hosts updated

  /series/{seriesId}/teams:
    put:
      summary: Update teams for a series
      tags:
        - Series
      parameters:
        - in: path
          name: seriesId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSeriesTeams'
      responses:
        '200':
          description: Teams updated

  /series/{seriesId}/formats:
    put:
      summary: Update formats for a series
      tags:
        - Series
      parameters:
        - in: path
          name: seriesId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSeriesFormats'
      responses:
        '200':
          description: Formats updated

components:
  schemas:
    Series:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [ BILATERAL, TRIANGULAR, QUADRANGULAR, LEAGUE ]
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateSeries:
      type: object
      required:
        - name
        - type
        - startDate
        - endDate
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [ BILATERAL, TRIANGULAR, QUADRANGULAR, LEAGUE ]
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        hostCountryIds:
          type: array
          items:
            type: string
        teamIds:
          type: array
          items:
            type: string
        formats:
          type: array
          items:
            type: object
            properties:
              format:
                type: string
                enum: [ TEST, ODI, T20 ]
              matchCount:
                type: integer

    UpdateSeries:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        type:
          type: string
          enum: [ BILATERAL, TRIANGULAR, QUADRANGULAR, LEAGUE ]
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time

    UpdateSeriesHosts:
      type: object
      required:
        - hostCountryIds
      properties:
        hostCountryIds:
          type: array
          items:
            type: string

    UpdateSeriesTeams:
      type: object
      required:
        - teamIds
      properties:
        teamIds:
          type: array
          items:
            type: string

    UpdateSeriesFormats:
      type: object
      required:
        - formats
      properties:
        formats:
          type: array
          items:
            type: object
            properties:
              format:
                type: string
                enum: [ TEST, ODI, T20 ]
              matchCount:
                type: integer
